version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://localhost:3000
    ports:
      - "80:80"
    restart: unless-stopped
    networks:
      - app-net
    depends_on:
      - backend
    volumes:
      - uploads:/app/uploads:ro

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      - PORT=${PORT:-3000}
      - NODE_ENV=${NODE_ENV:-production}
      - CLIENT_URL=${CLIENT_URL:-http://localhost:80}
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECRET=${COOKIE_SECRET}
      - UPLOAD_DIR=/app/uploads
      - MAX_UPLOAD_SIZE=${MAX_UPLOAD_SIZE:-5242880}
    volumes:
      - uploads:/app/uploads:rw
    networks:
      - app-net

volumes:
  uploads:
    driver: local

networks:
  app-net:
    driver: bridge 